In [1]:
import numpy as np

arr1 = np.array([[6, -8, 73, -110],
                 [np.nan, -8, 0, 94]])

print(arr1)

# Replace NaN with 0
res = np.nan_to_num(arr1, nan=0)
print("\n", res)

# Interchange rows
print("\n")
res[[0,1]] = res[[1,0]]
print("\n", res)

# Interchange columns
print("\n")
res[[0,1],[0,3]] = res[[0,1],[2,0]]
print(res)

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

 [[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]



 [[   0.   -8.    0.   94.]
 [   6.   -8.   73. -110.]]


[[ 0. -8.  0. 94.]
 [ 6. -8. 73.  6.]]
