In [1]:
import numpy as np

arr = np.array([
    [[7,8,9],
     [3,2,1],
     [13,14,15],
     [19,20,21]],

    [[7,8,9],
     [10,11,12],
     [16,17,18],
     [22,23,24]]
])

print("\n\n", arr, arr.shape)

a = np.moveaxis(arr, 0, 2)

print("\n\n", a, a.shape)



 [[[ 7  8  9]
  [ 3  2  1]
  [13 14 15]
  [19 20 21]]

 [[ 7  8  9]
  [10 11 12]
  [16 17 18]
  [22 23 24]]] (2, 4, 3)


 [[[ 7  7]
  [ 8  8]
  [ 9  9]]

 [[ 3 10]
  [ 2 11]
  [ 1 12]]

 [[13 16]
  [14 17]
  [15 18]]

 [[19 22]
  [20 23]
  [21 24]]] (4, 3, 2)
