In [1]:
import numpy as np

arr1 = np.array([
    [[41, 42], [43, 44]],
    [[45, 46], [47, 48]]
])

arr2 = np.array([
    [[29, 30], [31, 32]],
    [[33, 34], [35, 36]]
])

avg = (arr1 + arr2) / 2

print("Average of NumPy arrays:\n", avg)

print("\nMean of avg\n", np.mean(avg))

print("\nMedian of avg\n", np.median(avg))

values, counts = np.unique(avg, return_counts=True)
mode = values[np.argmax(counts)]

print("\nMode of avg\n", mode)

Average of NumPy arrays:
 [[[35. 36.]
  [37. 38.]]

 [[39. 40.]
  [41. 42.]]]

Mean of avg
 38.5

Median of avg
 38.5

Mode of avg
 35.0


In [2]:
import numpy as np
import pandas as pd

arr1 = np.array([
    [[41, 42], [43, 44]],
    [[45, 46], [47, 48]]
])

arr2 = np.array([
    [[29, 30], [31, 32]],
    [[33, 34], [35, 36]]
])

avg = (arr1 + arr2) / 2

mode = pd.Series(avg.reshape(-1)).mode()

print("Average of NumPy arrays:\n", avg)
print("\nMean =", np.mean(avg))
print("\nMedian =", np.median(avg))
print("\nMode =\n", mode)

Average of NumPy arrays:
 [[[35. 36.]
  [37. 38.]]

 [[39. 40.]
  [41. 42.]]]

Mean = 38.5

Median = 38.5

Mode =
 0    35.0
1    36.0
2    37.0
3    38.0
4    39.0
5    40.0
6    41.0
7    42.0
dtype: float64
